name: CI - Renovate - RBE

on:
  push:
    branches:
      - renovate/*
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source tree
        uses: actions/checkout@v4

  check-format:
    name: Check format
    if: github.repository_owner == 'DineshKumarRA' && needs.ci-renovate.outputs.commit == 'false'
    uses: ./.github/workflows/bazel.yml
    with:
      name: Check format script run
      caching: false
      ruby-version: jruby-9.4.8.0
      run: ./scripts/github-actions/check-format.sh

  test:
    name: Test
    if: github.repository_owner == 'seleniumhq' && needs.ci-renovate.outputs.commit == 'false'
    uses: ./.github/workflows/bazel.yml
    with:
      name: All RBE tests
      caching: false
      ruby-version: jruby-9.4.8.0
      run: ./scripts/github-actions/ci-build.sh

  ci-gh:
    if: github.repository_owner == 'seleniumhq' && needs.ci-renovate.outputs.commit == 'false'
    uses: ./.github/workflows/ci.yml
