name: Renovate

on:
  workflow_dispatch:
  
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.3.4
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
      - name: Repin Dependencies
        run: |
          REPIN=1 bazel run @maven//:pin
      - name: Commit and push changes
        run: |
          git config --global user.name 'selenium-ci
          git config --global user.email 'selenium-ci@users.noreply.github.com'
          git add maven_install.json
          git commit -m 'Repin maven dependencies'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
